export const RES_MESSAGE_MAPPING = {
    NO_CREDENTIALS: 'Không có thông tin xác thực.',
    INVALID_TOKEN: 'Token không hợp lệ',
    FORBIDDEN: 'Bạn không có quyền thực hiện hành động này.',
    BLOCKED_BY_CORS_POLICY: 'Bị chặn bởi chính sách bảo mật truy cập CORS.',
    INTERNAL_SERVER_ERROR: 'Lỗi không xác định từ phía server. Vui lòng thử lại sau.',
    INVALID_CREDENTIALS: 'Thông tin xác thực không hợp lệ.',
    NO_PERMISSION: 'Bạn không có quyền thực hiện hành động này.',
    USERNAME_EXISTED: 'Tên đăng nhập đã tồn tại.',
    EMAIL_EXISTED: 'Email đã tồn tại.',
    USER_NOT_FOUND: 'Người dùng không tồn tại.',
    INCORRECT_PASSWORD: 'Mật khẩu không chính xác.',
    INCORRECT_USERNAME_OR_PASSWORD: 'Tên đăng nhập hoặc mật khẩu không chính xác.',
    GOOGLE_AUTH_FAILED: 'Xác thực Google thất bại.',
    DATA_VALIDATION_FAILED: 'Dữ liệu không hợp lệ.',
    UPLOAD_IMAGE_FAILED: 'Tải ảnh lên thất bại.',
    DELETE_IMAGE_FAILED: 'Xóa ảnh thất bại.',
    EMAIL_VERIFICATION_FAILED: 'Email chưa được xác thực.',
    ROLE_NOT_FOUND: 'Không tìm thấy vai trò.',
    ROLE_EXISTED: 'Tên vai trò đã tồn tại.',
    ROLE_BEING_USED: 'Vai trò đang được sử dụng.',
    CATEGORY_NOT_FOUND: 'Không tìm thấy danh mục.',
    CATEGORY_EXISTED: 'Tên danh mục đã tồn tại.',
    CATEGORY_BEING_USED: 'Danh mục đang được sử dụng.',
    PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm.',
    PRODUCT_EXISTED: 'Tên sản phẩm đã tồn tại.',
    PRODUCT_ITEM_NOT_FOUND: 'Không tìm thấy chi tiết sản phẩm.',
    PRODUCT_IDS_MISMATCH: 'Các mã sản phẩm không khớp.',
    PRODUCT_BEING_USED: 'Sản phẩm đang được sử dụng.',

    SIGN_IN_SUCCESSFULLY: 'Đăng nhập thành công.',
    SIGN_UP_SUCCESSFULLY: 'Đăng ký thành công.',
    REFRESH_TOKEN_SUCCESSFULLY: 'Làm mới token thành công.',
    DEACTIVATE_ACCOUNT_SUCCESSFULLY: 'Hủy kích hoạt tài khoản thành công.',
    REACTIVATE_ACCOUNT_SUCCESSFULLY: 'Kích hoạt tài khoản thành công.',
    RESET_PASSWORD_EMAIL_SENT: 'Email đặt lại mật khẩu đã được gửi.',
    GOOGLE_AUTH_SUCCESSFULLY: 'Xác thực Google thành công.',
    RESET_PASSWORD_SUCCESSFULLY: 'Đặt lại mật khẩu thành công.',
    CHANGE_PASSWORD_SUCCESSFULLY: 'Thay đổi mật khẩu thành công.',
    UPLOAD_IMAGE_SUCCESSFULLY: 'Tải ảnh lên thành công.',
    DELETE_IMAGE_SUCCESSFULLY: 'Xóa ảnh thành công.',
    UPDATE_USER_SUCCESSFULLY: 'Cập nhật người dùng thành công.',
    CREATE_ROLE_SUCCESSFULLY: 'Tạo vai trò thành công.',
    UPDATE_ROLE_SUCCESSFULLY: 'Cập nhật vai trò thành công.',
    DELETE_ROLE_SUCCESSFULLY: 'Xóa vai trò thành công.',
    DEACTIVATE_CUSTOMER_SUCCESSFULLY: 'Khóa tài khoản khách hàng thành công.',
    CREATE_CATEGORY_SUCCESSFULLY: 'Tạo danh mục thành công.',
    UPDATE_CATEGORY_SUCCESSFULLY: 'Cập nhật danh mục thành công.',
    DELETE_CATEGORY_SUCCESSFULLY: 'Xóa danh mục thành công.',
    CREATE_PRODUCT_SUCCESSFULLY: 'Tạo sản phẩm thành công.',
    UPDATE_PRODUCT_SUCCESSFULLY: 'Cập nhật sản phẩm thành công.',
    DELETE_PRODUCT_SUCCESSFULLY: 'Xóa sản phẩm thành công.'
}

export const getMappedMessage = (originalMessage: string) => {
    return RES_MESSAGE_MAPPING[originalMessage as keyof typeof RES_MESSAGE_MAPPING] ?? originalMessage
}
